# Generated by Django 4.2.6 on 2023-10-06 20:50

from django.db import migrations
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_customuser_email_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', reviews.models.CustomUserManager()),
            ],
        ),
    ]
